export { PantallaInicio } from './PantallaInicio'
export { PantallaHoy, PantallaFeed } from './PantallaHoy'
export { PantallaRanking } from './PantallaRanking'
export { PantallaJuegos } from './PantallaJuegos'
export { PantallaChat } from './PantallaChat'
export { PantallaPerfil } from './PantallaPerfil'
export { PantallaAdmin } from './PantallaAdmin'
export { PantallaCompletarPerfil } from './PantallaCompletarPerfil'
